users/urls.py
from django.urls import path
from .  import views
from django.conf.urls import handler403


urlpatterns = [
    path('', views.user_home, name='home'),
    path('wishlist', views.user_wishlist, name='wishlist'), 
    path('toggle-wishlist/', views.toggle_wishlist, name='toggle_wishlist'),
    path('toggle-wishlist/<int:product_id>/', views.toggle_wishlist, name='toggle_wishlist'),
    
    path('wallet', views.user_wallet, name='wallet'),
    path('referral', views.user_referral, name='referral'),

    path('logout/', views.logout_page, name='logout'),
    path('login/', views.login_page, name='login'),
    path('login/forgot-password', views.forgot_password, name='forgot_password'),
    path('login/forgot-password/submit_otp', views.submit_otp, name='submit_otp'),
    path('login/forgot-password/submit_otp/resend_otp', views.resend_otp, name='resend_otp'),
    path('login/forgot-password/submit_otp/change_password', views.change_password, name='change_password'),
    path('register/', views.register_page, name='register'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name='activate'),

    path('user_profile/profile_info/', views.user_profile, name='user_profile'),
    path('user_profile/address/', views.address_management, name='address_management'),
    path('user_profile/get-address-details/<int:address_id>/', views.get_address_details, name='get_address_details'),
    path('user_profile/edit-address/<int:address_id>/', views.edit_address, name='edit_address'),
    path('user_profile/delete-address/<int:address_id>/', views.delete_address, name='delete_address'),
    path('user_profile/reset_password/', views.reset_password, name='reset_password'),

    # admin
    path('admin_login/', views.admin_login, name='admin_login'),
    path('admin_dashboard/', views.admin_dashboard, name='dashboard'),
    path('user_management/', views.user_management, name='user_management'),
    path('user_management/user_action/<action>/<id>/', views.user_action, name= 'user_action'),
    path('permission-denied/', views.permission_denied_view, name='permission_denied'),
]

zkart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    path('', include("users.urls")),
    path('', include("products.urls")),
    path('', include("orders.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

orders/models.py
from django.db import models
from users . models import *
from products . models import *
import uuid


class OrderAddress(models.Model):
    name = models.CharField(max_length=255)
    mobile = models.CharField(max_length=15, blank=True, null=True)
    address_line1 = models.CharField(max_length=255)
    address_line2 = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    pin_code = models.CharField(max_length=20)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    country = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}, {self.address_line1}, {self.city}, {self.state}, {self.country}"
    

class Coupon(models.Model):
    COUPON_TYPES = [
        ('percentage', 'Percentage'),
        ('amount', 'Amount'),
    ]

    coupon_code = models.CharField(max_length=50, unique=True)
    is_expired = models.BooleanField(default=False)
    discount = models.PositiveIntegerField(default=100)
    minimum_amount = models.FloatField(default=500.0, null=True, blank=True)
    description = models.CharField(max_length=250, null=True, blank=True)
    type = models.CharField(max_length=50, choices=COUPON_TYPES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.coupon_code
    
    class Meta:
        ordering = ['is_expired','-created_at']


class Order(models.Model):
    CUSTOMER_CHOICES = (
        ('cart', 'Cart'),
        ('deleted', 'Order Deleted'),
        ('placed', 'Order Placed'),
        ('completed', 'Order Completed'),
        ('cancelled', 'Order Cancelled'),
        ('pending', 'Pending'),
    )

    PAYMENT_CHOICES = (
        ('cod', 'Cash On Delivery'),
        ('paypal', 'PayPal'),
        ('razorpay', 'RazorPay'),
        ('wallet', 'Wallet'),
    )

    customer = models.ForeignKey(Account, related_name='account_orders', on_delete=models.SET_NULL, null=True, blank=True)
    status = models.CharField(default='cart', max_length=50, choices=CUSTOMER_CHOICES)
    order_identifier = models.CharField(max_length=100, editable=True, null=True, blank=True) #unique=True
    address = models.ForeignKey(OrderAddress, related_name='order_address', on_delete=models.SET_NULL, null=True, blank=True)
    order_date = models.DateTimeField(null=True, blank=True)
    complete_date = models.DateTimeField(null=True, blank=True)
    total_amount = models.FloatField(default=0.0, null=True, blank=True)
    delivery_charge = models.FloatField(default=0.0, null=True, blank=True)
    total_discount = models.FloatField(default=0.0, null=True, blank=True)
    coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL, null=True, blank=True)
    payment_method = models.CharField(max_length=50, null=True, blank=True, choices=PAYMENT_CHOICES)
    payment_id = models.CharField(max_length=100, blank=True, null=True)
    special_instructions = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.customer.user.username} + {self.status} + {self.id}'
    
    class Meta:
        ordering = ['-created_at']
    
    def get_cart_total(self):
        order_items = self.order_items.all()
        total = sum([item.get_total() for item in order_items])
        return total
    
    def get_cart_discount(self):
        order_items = self.order_items.all()
        total = sum([item.get_discount() for item in order_items])
        return total
    
    def get_cart_quantity(self):
        order_items = self.order_items.all()
        total = sum([item.quantity for item in order_items])
        return total 
    
    def order_total_basic(self):
        order_items = self.order_items.all()
        total = sum([item.selling_price*item.quantity for item in order_items])
        return total

    def coupon_discount(self):
        order_items = self.order_items.all()
        total_coupon_discount = sum([item.coupon_discount for item in order_items])
        return total_coupon_discount

    def order_total_amount(self):
        order_items = self.order_items.all()
        total = sum([(item.selling_price)*item.quantity for item in order_items])
        return total + self.delivery_charge - self.coupon_discount()
    
    def order_total_saved(self):
        order_items = self.order_items.all()
        total = sum([(item.original_price - item.selling_price)*item.quantity for item in order_items])
        return total + self.coupon_discount()

    def order_payment_status(self):
        order_items = self.order_items.all()
        result = []
        for i in order_items:
            result.append(i.payment_status)

        return False if 'pending' in result or 'pending' in result or 'cancelled' in result  else True
    
    def is_completed(self):
        order_items = self.order_items.all()
        for item in order_items:
            if not item.completed_date:
                return False
        return True
    

class OrderItem(models.Model):
    SELLER_CHOICES = (
        ('cart', 'Cart'),
        ('in_progress', 'In Progress'),
        ('shipped', 'Shipped'),
        ('delivered', 'Delivered'),
        ('cancelled', 'Cancelled'),
        ('return_request', 'Requested for Return'),
        ('returned', 'Returned'),
        ('pending', 'Pending'),
    )
    
    PAYMENT_ABOUT= (
        ('pending', 'Pending'),
        ('failed', 'Failed'),
        ('success', 'Success'),
        ('cancelled', 'Cancelled'),
        ('wallet', 'Added to Wallet'),
    )

    product_variant = models.ForeignKey(ProductVariant, related_name='ordered_product', on_delete=models.SET_NULL, null=True, blank=True)
    order = models.ForeignKey(Order, related_name='order_items', on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.PositiveIntegerField(default=0, null=True, blank=True)
    status = models.CharField(max_length=50, default='cart', choices=SELLER_CHOICES, null=True, blank=True)
    selling_price = models.FloatField(default=0.0, null=True, blank=True)
    original_price = models.FloatField(default=0.0, null=True, blank=True)
    coupon_discount = models.FloatField(default=0.0, null=True, blank=True)
    # delivery_charge_deduction = models.FloatField(default=None, null=True, blank=True)
    subtotal = models.FloatField(default=0.0, null=True, blank=True)
    order_date = models.DateTimeField(null=True, blank=True)
    completed_date = models.DateTimeField(null=True, blank=True)
    return_date = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    payment_status = models.CharField(max_length=50, default='pending', choices=PAYMENT_ABOUT, null=True, blank=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.product_variant.product.title} + {str(self.quantity)} + {self.order}'
    
    def get_total(self):
        product_selling_price = self.product_variant.product.product_selling_price()
        return product_selling_price  * self.quantity

    def get_discount(self):
        product_difference = self.product_variant.product.original_price - self.product_variant.product.product_selling_price()
        discount = product_difference * self.quantity
        return discount
    
    def get_discount_percentage(self):
        discount_percentage = self.product_variant.product.offer_percentage()
        return round(discount_percentage)

    def item_discount(self):
        discount = (self.original_price - self.selling_price) * self.quantity
        return discount
    
    def item_total(self):
        total = (self.selling_price * self.quantity)
        return total
    
    def item_grand_total(self):
        total = (self.selling_price * self.quantity) - self.coupon_discount
        return total
    
    def item_grand_discount(self):
        discount = self.item_discount() + self.coupon_discount
        return discount

templates/admin_page/order_management/order_item_management.html
{% extends 'admin_page/layout/main.html' %}
{% load static %}

{% block header %}
<style>
  img {
      max-width: 120px;
      margin-right: 20px;
  }
  .tm-product-table-container {
        overflow-x: scroll !important;
    }

  th{
    white-space: nowrap; padding-left: 20px; padding-right: 20px;
  }


  .status-select {
      display: none;
  }

  .tm-product-table-container {
    max-height: 800px;
  }
</style>
{% endblock header %}


{% block content %}
<div class="container-fluid mt-5">
  <div class="row tm-content-row d-flex justify-content-center">
      <div class="col-md-12 col-xl-10 tm-block-col">
        
        {% if messages %}
        <div class="alert-container">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <h4 style="color: white;">Order Items</h4>

          <div class="tm-bg-primary-dark tm-block tm-block-products" style="min-height: 1000px;">
              <div class="tm-product-table-container table-responsive">
                  <table class="table table-hover tm-table-small tm-product-table">
                      <thead class="thead-light">
                          <tr>
                              <th scope="col">&nbsp;</th>
                              <th scope="col">Product Details</th>
                              <th scope="col">Price Details</th>
                              <th scope="col">Discount Details</th>
                              <th scope="col">Stock Details</th>
                              <th scope="col">Total</th>
                              <th scope="col">Completed Date</th>
                              <th scope="col">Payment Status</th>
                              <th scope="col">Order Status</th>
                              <th scope="col">&nbsp;</th>
                          </tr>
                      </thead>
                      <tbody>
                          {% for order_item in order %}
                          <tr>
                              <td scope="row">
                                  <img src="{{order_item.product_variant.product.product_images.all.0.product_image.url}}" alt="Product Image" width="100">
                              </td>
                              <td class="tm-product-name" style="min-width: 400px;">
                                  <p>{{order_item.product_variant.product.title}}</p>
                                  <p><strong>Brand:</strong> {{order_item.product_variant.product.brand}}</p>
                                  <p><strong>Color:</strong> {{order_item.product_variant.color.name}} <strong class="ml-3">Size:</strong> {{order_item.product_variant.size.name}}</p>
                              </td>
                              <td style="white-space: nowrap; padding: 0 20px;">
                                  <p>Original Price: ₹{{order_item.original_price|floatformat:0}}</p>
                                  <p><strong>Selling Price:</strong> ₹{{order_item.selling_price|floatformat:0}}</p>
                              </td>
                              <td style="white-space: nowrap;">
                                <p>Saved Amount: ₹{{order_item.item_discount|floatformat:0}}</p>
                                <p>
                                    Coupon: 
                                    {% if order_item.order.coupon %}
                                    ₹{{order_item.coupon_discount|floatformat:0}} <span style="color: cornflowerblue;">({{order_item.order.coupon}})</span>
                                    {% else %}
                                    NO Coupon Applied
                                    {% endif %}
                                  </p>
                              </td>
                              <td style="white-space: nowrap; padding: 0 20px;">
                                  <p>Purchased Quantity: <strong>{{order_item.quantity}}</strong></p>
                                  <p>Total Quantity Left: <strong>{{order_item.product_variant.quantity}}</strong></p>
                              </td>
                              <td style="white-space: nowrap; padding: 0 20px;">
                                <p>Sub Total: <strong>₹ {{order_item.item_total|floatformat:0}}</strong></p>
                                <p>Grand Total: <strong>₹ {{order_item.item_grand_total|floatformat:0}}</strong></p>
                              </td>
                              <td style="white-space: nowrap; padding: 0 20px;">
                                  <p>
                                      {% if order_item.completed_date %}
                                      {{ order_item.completed_date|date:"d M H:i" }}
                                      {% else %}
                                      Pending
                                      {% endif %}
                                  </p>
                              </td>
                              <td style="white-space: nowrap; padding: 0 20px;">
                                  <p>
                                      {% if order_item.payment_status == 'success' %}
                                      <span style="color: rgb(115, 231, 115); font-size: large;">{{order_item.payment_status}}</span>
                                      {% else %}
                                      <strong>
                                        <span style="color: rgb(105 3 3); font-size: large;">{{order_item.payment_status}}</span>
                                      </strong>
                                      {% endif %}
                                  </p>
                              </td>
                              <td>
                                <div class="text-center"
                                {% if order_item.status == 'delivered' %}
                                style="background-color: green; color: black;"
                                {% elif order_item.status == 'in_progress' or order_item.status == 'shipped' %}
                                style="background-color: yellow; color: black;"
                                {% elif order_item.status == 'cancelled' %}
                                style="background-color: red; color: black;"
                                {% elif order_item.status == 'returned' %}
                                style="background-color: blueviolet; color: white;"
                                {% else %}
                                style="background-color: black; color: white;"
                                {% endif %}
                                >
                                <p id="status-display-{{ order_item.id }}">{{ order_item.get_status_display }}</p>
                                </div>
                                    
                                  <form id="status-form-{{ order_item.id }}" action="{% url 'update_order_status' order_item.id %}" method="POST" style="display: inline;">
                                      {% csrf_token %}
                                      <select name="status" class="form-select status-select" id="status-select-{{ order_item.id }}">
                                          <option value="in_progress" {% if order_item.status == 'in_progress' %}selected{% endif %}>In Progress</option>
                                          <option value="shipped" {% if order_item.status == 'shipped' %}selected{% endif %}>Shipped</option>
                                          <option value="delivered" {% if order_item.status == 'delivered' %}selected{% endif %}>Delivered</option>
                                          <option value="cancelled" {% if order_item.status == 'cancelled' %}selected{% endif %}>Cancelled</option>
                                        </select>
                                  </form>
                              </td>
                              <td>
                                {% if order_item.status == 'in_progress' or order_item.status == 'shipped' %}
                                <button class="btn btn-primary" onclick="toggleEditStatus(event, {{ order_item.id }})">Update</button>
                                {% endif %}
                              </td>
                          </tr>
                          {% endfor %}
                      </tbody>
                  </table>
              </div>
          </div>
      </div>
  </div>
</div>
{% endblock content %}


{% block post_footer %}

{% endblock post_footer %}
  

{% block scripts %}
<script>
  function toggleEditStatus(event, orderItemId) {
      event.stopPropagation();  // Prevent row click event
      const statusDisplay = document.getElementById(`status-display-${orderItemId}`);
      const statusSelect = document.getElementById(`status-select-${orderItemId}`);
      const button = event.target;

      if (statusSelect.classList.contains('status-select')) {
        console.log('first')
          // Show select and change button text to Save
          statusSelect.classList.remove('status-select');
          statusDisplay.classList.add('status-select');
          button.textContent = 'Save';
          button.onclick = function(event) {
              event.stopPropagation();
              document.getElementById(`status-form-${orderItemId}`).submit();
          };
      } else {
        console.log('sec')
          // Hide select, show display, change button text to Update
          statusSelect.classList.add('status-select');
          statusDisplay.classList.remove('status-select');
          statusDisplay.textContent = statusSelect.options[statusSelect.selectedIndex].text;
          button.textContent = 'Update';
          button.onclick = function(event) {
              event.stopPropagation();
              toggleEditStatus(event, orderItemId);
          };
      }
  }
</script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.min.js"></script>

{% endblock scripts %}

templates/admin_page/order_management/order_management.html
{% extends 'admin_page/layout/main.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css">

<style>
    .table{
      background-color: white;
      color: black;
      font-weight: 400;
    }

    .table-responsive {
        overflow-x: auto;
        overflow-y: auto;
        max-width: 100%;
        max-height: 70vh; 
    }
    .table-hover tbody tr:hover {
        cursor: pointer;
        color: black;
    }
    .table th, .table td {
        white-space: wrap;
    }
    .table th:nth-child(1), .table td:nth-child(1) { /* Delivery Address */
        max-width: 200px;
    }
    .table th:nth-child(6), .table td:nth-child(6) { /* Delivery Address */
        min-width: 250px;
    }
    .table th:nth-child(4), .table td:nth-child(4) { /* Products */
        min-width: 150px;
    }
    .table th:nth-child(7), .table td:nth-child(7) { /* Order Note */
      white-space: nowrap;
      max-width: 350px;
    }
</style>
{% endblock header %}


{% block content %}
<div class="container-fluid " style="background-color: black; padding: 50px 5rem 100px;">
  {% if messages %}
  <div class="alert-container">
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }}" role="alert">
          {{ message }}
      </div>
      {% endfor %}
  </div>
  {% endif %}

  <h4 style="color: white;">Order Management</h4>

  <div class="col-md-6 my-4">
    <form class="d-flex" method="get" role="search">
        <input name="search" class="form-control me-2 bg-light text-dark" type="search" placeholder="Search" aria-label="Search" 
        {% if search %} value="{{search}}" {% endif %}>
        <button class="btn btn-success ml-3" type="submit">Search</button>
    </form>      
  </div>

  <div class="table-responsive">
      <table class="table table-hover table-bordered">
          <thead class="thead-dark">
              <tr>
                  <th>Order ID</th>
                  <th >Username</th>
                  <th>Status</th>
                  <th>Products</th>
                  <th>Payment Method</th>
                  <th>Delivery Address</th>
                  <th>Order Note</th>
                  <th>Delivery Charge</th>
                  <th>Coupon</th>
                  <th>Discount</th>
                  <th>Total</th>
                  <th>Date Ordered</th>
                  <th>Date Completed</th>
              </tr>
          </thead>
          <tbody>
              {% for order in orders %}
              <tr onclick="redirectToOrderActionPage('{{order.id}}')">
                  <td>{{order.order_identifier}}</td>
                  <td style="white-space: nowrap;">{{order.customer.user.username}}</td>
                  <td style="white-space: nowrap;">
                    {% if not order.is_completed %}
                    <span style="color: rgb(173, 173, 17);">{{order.get_status_display}}</span>
                    {% else %}
                    <span style="color: #007bff;">{{order.get_status_display}}</span>
                    {% endif %}
                  </td>
                  <td style="white-space: nowrap;">
                    {% for order_item in order.order_items.all %}
                    <div class="d-flex mb-2 align-items-center" >
                      
                      <div class="d-flex align-items-center p-1"
                        {% if order_item.status == 'delivered' %}
                        style=" background-color: green; color: black;"
                        {% elif order_item.status == 'in_progress' or order_item.status == 'in_progress' %}
                        style="background-color: yellow; color: black;"
                        {% elif order_item.status == 'cancelled' %}
                        style="background-color: red; color: black;"
                        {% elif order_item.status == 'returned' %}
                        style="background-color: blueviolet; color: white;"
                        {% else %}
                        style="background-color: black; color: white;"
                        {% endif %}
                        >
                        <p class="mb-0" id="status-display-{{ order_item.id }}">{{ order_item.get_status_display }}</p>
                      </div>
                      <p class="ml-4 mb-0">{{order_item.product_variant.product.title}}</p>
                      
                    </div>
                    {% endfor %} 
                  </td>

                  <td>
                    {{order.get_payment_method_display}}
                  </td>

                  <td>
                    <p class="mb-1">{{order.address.name}}</p>
                    <p class="mb-1">{{order.address.mobile}}</p>
                    <p class="mb-1">{{order.address.pin_code}}, {{order.address.city}}</p>
                  </td>
                  <td style="white-space: wrap; min-width: 250px;">{{order.special_instructions}}</td>
                  <td>
                    {% if order.delivery_charge %}
                    ₹ {{order.delivery_charge|floatformat:0}}
                    {% else %}
                    <span style="color: #007bff;">FREE</span>
                    {% endif %}
                  </td>
                  <td style="white-space: nowrap;">
                    {% if order.coupon %}
                    <p style="color: green;">{{order.coupon}}</p>
                    <p>₹ {{order.coupon_discount|floatformat:0}}</p>
                    {% else %}
                    <span style="color: firebrick;">No Coupon</span>
                    {%endif%}
                  </td>
                  <td style="white-space: nowrap;">₹ {{order.order_total_saved|floatformat:0}}</td>
                  <td style="white-space: nowrap;">₹ {{order.order_total_amount|floatformat:0}}</td>
                  <td style="white-space: nowrap;">{{order.order_date}}</td>
                  <td style="white-space: nowrap;">
                    {% if order.complete_date %}
                    <span style="color: #007bff;">{{order.complete_date}}</span>
                    {% else %}
                    Not Completed Yet
                    {% endif %}
                  </td>
              </tr>
              {% endfor %}
          </tbody>
      </table>
  </div>
</div>
{% endblock content %}


{% block post_footer %}

{% endblock post_footer %}
  

{% block scripts %}
<script>
  function redirectToOrderActionPage(orderId) {
      window.location.href = '/order-item-management/' + orderId + '/';
  }
</script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.min.js"></script>

{% endblock scripts %}

templates/admin_page/order_management/pdf_sales_report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sales Report PDF</title>
    <style>
         @page { 
            size: landscape; 
            margin: 1cm; 
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid black;
            padding: 4px 0 0 0 ;
            margin: 0 0 0 0;
            text-align: center;
            word-wrap: break-word;
            
        }
        td{
            font-size: 13px;
        }
        th {
            background-color: #f2f2f2;
        }
        .nowrap {
            white-space: nowrap;
        }
        p{
            font-size: large;
        }

    </style>
</head>
<body>
    <h5 ><strong>Overall details</strong></h5>

    <p style="color: blue;">Overall Order Count: <strong >{{overall_order_items}}</strong></p>
    <p style="color: green; padding-left: 5px;">Overall Order Amount: <strong >RS. {{overall_order_amount|floatformat:0}}</strong></p>
    <p style="color: red;">Overall Order Discount: <strong >RS. {{overall_order_discount|floatformat:0}}</strong></p>

    <h2>Sales Report</h2>
    <table class="table table-bordered table-hover table-dark">
        <thead class="thead-dark">
            <tr>
                <th style="width: 180px;">Order Id</th>
                <th class="nowrap" style="width: 100px;">Username</th>
                <th class="nowrap" style="width: 80px;">Order Date</th>
                <th class="nowrap" style="width: 70px;">OG Price</th>
                <th class="nowrap" style="width: 70px;">Sold Price</th>
                <th class="nowrap" style="width: 40px;">Qty</th>
                <th class="nowrap" style="width: 170px;">Coupon Applied</th>
                <th class="nowrap">Total Amount</th>
                <th class="nowrap">Order Item Status</th>
                <th class="nowrap">Payment Status</th>
                <th class="nowrap">Payment Method</th>
            </tr>
        </thead>
        <tbody>
            {% for order_item in order_items %}
            <tr class="table-light">
                <td >{{ order_item.order.order_identifier }}</td>
                <td class="nowrap">{{ order_item.order.customer.user.username }}</td>
                <td class="nowrap">{{ order_item.order.order_date|date:"d/m/Y" }}</td>
                <td class="nowrap">{{ order_item.original_price|floatformat:0 }}</td>
                <td class="nowrap">{{ order_item.selling_price|floatformat:0 }}</td>
                <td class="nowrap" style="padding: 0; margin: 0;">{{ order_item.quantity }}</td>
                <td class="nowrap">
                    {% if order_item.order.coupon %}
                    {{ order_item.order.coupon.coupon_code }} ({{ order_item.coupon_discount|floatformat:0 }})
                    {% else %}
                    'N/A'
                    {% endif %}
                </td>
                <td class="nowrap">{{ order_item.item_grand_total|floatformat:0 }}</td>
                <td class="nowrap">{{ order_item.status }}</td>
                <td class="nowrap">{{ order_item.payment_status }}</td>
                <td class="nowrap">{{ order_item.order.payment_method }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>